### ISSUE TITLE
Overlay Optimization

### ISSUE THREAD

**Issue by Ansh4011** [aleksey-hoffman/sigma-file-manager#132]
### Is there an existing issue for this?

- [X] I have searched the opened issues

### Problem description

The window transparency effect looks really pretty, but there is one minor drawback that it overlays over everything, over those things as well where it is not needed as in the top bar in the image which looks a bit untidy. 
![image](https://user-images.githubusercontent.com/84930340/130045791-8f8db58b-4fef-4283-9c6b-39f0cb47c75f.png)

### Steps to reproduce

1. Apply the window transparency effect from the settings.

### Environment

- OS: Windows 10~21H1
- App version: v1.3.0

**Comment by aleksey-hoffman** [comment]
From my tests I found out that it looks better when everything is covered.
Though I might add a setting for adjusting which elements are covered.

I also want to add separate settings for the home page, so it would be possible to configure the overlay for it independently.

**Comment by Ansh4011** [comment]
> From my tests I found out that it looks better when everything is covered.

Indeed, but it also highly depends over the image used for the overlay as well, in my opinion. 
> Though I might add a setting for adjusting which elements are covered.
> 
> I also want to add separate settings for the home page, so it would be possible to configure the overlay for it independently.

That would be really nice and sounds cool. Thanks :)

**Comment by Ansh4011** [comment]
Btw, can you increase the animation on hover time for the context menu previews as you did for the left side ribbon, that would make it look really fast and snappy. 
![image](https://user-images.githubusercontent.com/84930340/130100587-674926f4-a896-46d3-b39c-d32302358769.png)

**Comment by aleksey-hoffman** [comment]
> can you increase the animation on hover time for the context menu previews

That's how it was before. 
Initially there was 0ms delay. but I increased it to 200ms because otherwise every time you open the context menu the cursor triggers the preview (tooltip) of the first icon. So by delaying the tooltip I'm avoiding this problem.

The context menu top left corner starts from the cursor, right? So when you move the cursor down, you always trigger the tooltip of the first icon.

**Comment by aleksey-hoffman** [comment]
> can you increase the animation on hover time for the context menu previews

That's how it was before. 
Initially there was 0ms delay. but I increased it to 200ms because otherwise every time you open the context menu the cursor triggers the preview (tooltip) of the first icon.

The context menu top left corner starts from the cursor, right? So when you open the context menu and move the cursor down, you always trigger the tooltip of the first icon.

So by delaying the tooltip I'm avoiding this problem.

**Comment by Ansh4011** [comment]
> > can you increase the animation on hover time for the context menu previews
> 
> That's how it was before.
> Initially there was 0ms delay. but I increased it to 200ms because otherwise every time you open the context menu the cursor triggers the preview (tooltip) of the first icon.
> 
> The context menu top left corner starts from the cursor, right? So when you open the context menu and move the cursor down, you always trigger the tooltip of the first icon.
> 
> So by delaying the tooltip I'm avoiding this problem.

Yupp... I totally agree! Thanks :)
