### ISSUE TITLE
[Feature request] Support for OneDrive and OneDrive for Business

### ISSUE THREAD

**Issue by OfficialEsco** [aleksey-hoffman/sigma-file-manager#3]
## Feature request:
OneDrive should be easily accessible from the Home Page IF the user uses it.
Atm Sigma instantly downloads the photos/(probably files) when entering the folder.

**Comment by aleksey-hoffman** [comment]
Fixed in 574787c
Will be released in v1.4 (on Saturday)

**Comment by aleksey-hoffman** [comment]
Fixed in 574787c
Will be released in v1.4 (on Saturday)

## Home page

OneDrive card will be displayed on the drive list and navigation panel

![image](https://user-images.githubusercontent.com/61761672/131690218-495c6c69-1f26-47de-92c6-a286a9a8f895.png)

## Navigator

Offline status will be displayed on the item card if the file is offline (size on disk is 0)

![image](https://user-images.githubusercontent.com/61761672/131690515-dbc2148e-3e7d-4e73-89df-3e66cce3d8e3.png)
