### ISSUE TITLE
Slow Animations

### ISSUE THREAD

**Issue by Ansh4011** [aleksey-hoffman/sigma-file-manager#64]
## Problem: 
The animations in my opinion seem to be pretty slow, and make the software appear to be slow though it isn't.... If the animations have decreased time, the software will look quite much faster and snappier.... Another thing can be done that, if the mouse stays over the button for 2 or 3 seconds only then the summary of button will be displayed! Have a look at the screenshot for reference! Thanks!
![image](https://user-images.githubusercontent.com/84930340/119944065-73550380-bfb1-11eb-8f14-8970d12f690b.png)

**Comment by aleksey-hoffman** [comment]
I will soon add an option to disable some animations / transitions.

As for the tooltips, I'm not sure it would be better to delay them for 2 seconds instead of showing them immediately. Wouldn't it make the app feel slow / unresponsive? Maybe I can add a setting and let users control the delay time.

**Comment by Venitros** [comment]
The instantly appearing tooltips make it look really messy when moving the mouse around the icons. The tooltip timing is good in the right click menu of files and folders. This is what I mean: [Google drive video](https://drive.google.com/file/d/1Ju0rS2h9kHSsZncAm69-dIdTJrHb5naW/view)
You could also try to condense the tooltips a bit more, there's quite a lot of empty space in them. Perhaps also making the tooltip background transparency adjustable.

I would love it if you could add a toggle for fast animations, rather than no animations. I like having animations in programs, as long as they do not interrupt or slow down my actions. For example the animation when switching between the home page, navigator, dashboard, etc. Making that animation twice as fast would still look nice, while making the program feel more responsive.

**Comment by aleksey-hoffman** [comment]
@Venitros yeah, tooltips should not overlap like this, it's a bug.
I will fix this and add the ability to control animation speed in one of the next updates.

**Comment by aleksey-hoffman** [comment]
**Tooltip transition overlap bug**: 
Fixed in 876769d

**Slow page transitions**: 
Fixed in 3fae2d0
